### ISSUE TITLE
Bhavcopy virus infected

### ISSUE THREAD

**Issue by ramit18** [hemenkapadia/getbhavcopy#13]
Hello, 

My windows defender deleted the existing bhavcopy setup since it was showing "infected by a virus".  I tried to download the setup again from the website but the windows defender stopped it from downloading stating it contains a virus.  Therefore, kindly inform if I should change my windows setting or is it seriously infected by a virus?.

**Comment by hemenkapadia** [comment]
Can you confirm 
- you downloaded Getbhavcopy from https://github.com/hemenkapadia/getbhavcopy/releases
- the build version of Getbhavcopy is 2.1.10.40405
- and the MD5 sum of Getbhavcopy.exe file matches e3ecb28e59609f50ccdff573fd4caa1b

If you can confirm all the three above, especially the build version and the MD5 sum then do not worry. It is a false positive being detected by windows defender. This is most likely due to the obfuscation strategy I use to protect disassembly of Getbhavcopy executable.

**Comment by ramit18** [comment]
Thank you, Hemen...!! 

I have downloaded it again and now working good.  Thanks again...

**Comment by hemenkapadia** [comment]
Ok. Generally do not download Getbhavcopy from any other site than the download link on www.getbhavcopy.com.
