### ISSUE TITLE
Option to remove BSE Index Data

### ISSUE THREAD

**Issue by harshil4722** [hemenkapadia/getbhavcopy#7]
Hi Hemant,

Thank you for making such a useful tool. 

One question, is it possible to not download the BSE Index data, so that one can download all the historical bhavcopies of all the stocks quickly? Index data from BSE takes much longer to download compared to the entire daily bhavcopy of the stocks. On the NSE tab in options, i see that you did include the functionality to ignore the NSE Index data, but this would be very helpful if this option is included on the BSE settings as well.

Regards,

Harshil

**Comment by hemenkapadia** [comment]
Interesting enhancement request. Will look into this.

**Comment by hemenkapadia** [comment]
NSE options tab does not provide any configurable option to skip downloading Indices data. No such functionality is planned either. With the fix for 2.1.11a BSE indices data download issue should resolve too.

Decided not to provide this functionality in the tool unless there are multiple requests. For now closing this enhancement as Wont Fix

**Comment by ankush30** [comment]
I would certainly request to have option not to download BSE indices as its very time consuming on daily basis.
