### ISSUE TITLE
Deewali Murat trading day 27-10-2019 NSE, BSE & NSE F&O EOD Data unable to download

### ISSUE THREAD

**Issue by Mahi-1983** [hemenkapadia/getbhavcopy#97]
while downloading data on 27-10-2019 , showing data download complete,
please verify the same
thanks for supporting for downloading data

Mahi

**Comment by hemenkapadia** [comment]
@Mahi-1983, I believe this is what you see when you try downloading data for 2th October 2019, the Diwali Muhurat trading. 

![image](https://user-images.githubusercontent.com/9943123/68549741-6e6d3680-03b0-11ea-825c-77ef05e6ab44.png)

This is because, by default, Getbhavcopy is configured to __not download__ data for the weekend. Since this time the Muhurat trading was on a Sunday, the data is not getting downloaded for that day.

![image](https://user-images.githubusercontent.com/9943123/68549846-a7f27180-03b1-11ea-98a4-3f5ca04c2e7c.png)


To download data for a weekend trading day you can temporarily disable this option as mentioned below

- Uncheck the Ignore Weekend checkbox. Save the options.
- Download the data for the weekend day, in this case the muhurat.
- Once the data is downloaded, go back to options and re-enable the Ignore  Weekend option and save.

**Comment by Mahi-1983** [comment]
Dear Hemen,
Thank you for valuable response and solution.
Warm Regards,
Mahi
    On Monday, 11 November, 2019, 01:44:57 am IST, Hemen Kapadia <notifications@github.com> wrote:  
 
 
Closed #97.
